name: Build App

on:
  push:
    branches:
      - '*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

  build:
    name: Build app
    needs: check_wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false

      - name: Build app
        run: ./gradlew --no-daemon assembleRelease

      - name: Rename app
        run: |
          cd app/build/outputs/apk/release
          mv app-release-unsigned.apk QuickNovel.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickNovel
          path: app/build/outputs/apk/release/QuickNovel.apk
